In [118]:
import numpy as np

In [119]:
np.set_printoptions(precision=2,linewidth=100,suppress=True)

#**Load Data**

In [120]:
raw_data = np.genfromtxt("/content/loan-data.csv", delimiter=';', skip_header=1, autostrip=True,
                         encoding = "cp855")

raw_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

#**Checking for missing values**

In [121]:
np.isnan(raw_data).sum()

88005

In [122]:
temp_fill = np.nanmax(raw_data) + 1
# mean for each col
temp_mean = np.nanmean(raw_data, axis=0)

<ipython-input-122-131581a62730>:3: RuntimeWarning: Mean of empty slice
  temp_mean = np.nanmean(raw_data, axis=0)


In [123]:
temp_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

**Stats for each column**

In [124]:
temp_stats = np.array([np.nanmin(raw_data,axis=0),
                      temp_mean,
                      np.nanmax(raw_data,axis=0)])

<ipython-input-124-c01efb3a0b60>:1: RuntimeWarning: All-NaN slice encountered
  temp_stats = np.array([np.nanmin(raw_data,axis=0),
<ipython-input-124-c01efb3a0b60>:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data,axis=0)])


In [125]:
temp_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

#**Splitting the dataset into numerical & string data**

In [126]:
col_strings = np.argwhere(np.isnan(temp_mean)).squeeze()
col_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [127]:
col_numeric = np.argwhere(np.isnan(temp_mean) == False).squeeze()
col_numeric

array([ 0,  2,  4,  6,  7, 13])

**Re-importing the datase**

In [128]:
data_string = np.genfromtxt("/content/loan-data.csv",
                            delimiter=';',
                            skip_header=1,
                            autostrip=True,
                            encoding = "cp855",
                            usecols=col_strings,
                            dtype=str)
data_string

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [129]:
data_numeric = np.genfromtxt("/content/loan-data.csv",
                            delimiter=';',
                            skip_header=1,
                            autostrip=True,
                            encoding = "cp855",
                            usecols=col_numeric,
                            filling_values=temp_fill)
data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

**The names of the columns**

In [130]:
header = np.genfromtxt("/content/loan-data.csv",
                            delimiter=';',
                            skip_footer=raw_data.shape[0],
                            autostrip=True,
                            encoding = "cp855",
                            dtype=str)
header

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [131]:
header_string, header_numeric = header[col_strings], header[col_numeric]
print(header_string)
print(header_numeric)

['issue_d' 'loan_status' 'term' 'grade' 'sub_grade' 'verification_status' 'url' 'addr_state']
['id' 'loan_amnt' 'funded_amnt' 'int_rate' 'installment' 'total_pymnt']


#**Creating check points**

In [132]:
def checkpoint(file_name, cp_header, cp_data):
  np.savez(file_name,header=cp_header, data=cp_data)
  cp_variable = np.load(file_name+".npz")
  return (cp_variable)

In [133]:
cp_test = checkpoint("checkpoint-data", header_string, data_string)

In [134]:
cp_test['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [135]:
cp_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [136]:
np.array_equal(cp_test['data'], data_string)

True

#**Manipulating string columns**

**Issue Date**

In [137]:
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [138]:
header_string[0] = 'Issue_date'

In [139]:
data_string

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [140]:
np.unique(data_string[:,0])
# mnt - year

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

strip -15 since all the dates are in the same year

In [141]:
data_string[:,0] = np.chararray.strip(data_string[:,0],'-15')
data_string[:,0]

array(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

In [142]:
np.unique(data_string[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

Represent month values as integers

In [143]:
months = np.array(['','Jan','Feb','Mar', 'Apr', 'May','Jun','Jul', 'Aug', 'Sep','Oct','Nov', 'Dec'])

for i in range(13):
  data_string[:,0] = np.where(data_string[:,0]==months[i],i,data_string[:,0])

data_string[:,0]

array(['5', '0', '9', ..., '6', '4', '12'], dtype='<U69')

**Loan Status**

In [144]:
header_string

array(['Issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [145]:
np.unique(data_string[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [146]:
#number of unique elements
np.unique(data_string[:,1]).size

9

Only care if the candidate is in a stable financial condition.   
Create variable to split status value in good or bad.   
Good --> 1   
Bad --> 0

In [147]:
status_bad = np.array(['', 'Charged Off','Default', 'Late (31-120 days)'])
data_string[:,1] = np.where(np.isin(data_string[:,1],status_bad),0,1)

In [148]:
np.unique(data_string[:,1])

array(['0', '1'], dtype='<U69')

**Term**

In [149]:
header_string

array(['Issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [150]:
np.unique(data_string[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

Remove the " months"

In [151]:
data_string[:,2] = np.chararray.strip(data_string[:,2]," months")
np.unique(data_string[:,2])

array(['', '36', '60'], dtype='<U69')

In [152]:
header_string[2] = "term_months"
header_string

array(['Issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

Assign 60 to each empty space.   
If we have missing values in CRM, we asume the worst.

In [153]:
data_string[:,2] = np.where(data_string[:,2] == '', 60, data_string[:,2])
np.unique(data_string[:,2])

array(['36', '60'], dtype='<U69')

**Grade and Sub-grade**

In [154]:
header_string

array(['Issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [155]:
np.unique(data_string[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [156]:
np.unique(data_string[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

Substitute empty spaces in Sub-grade

In [157]:
for i in np.unique(data_string[:,3])[1:]:
  data_string[:,4] = np.where((data_string[:,4] == '') & (data_string[:,3] == i), i+'5', data_string[:,4])
np.unique(data_string[:,4], return_counts=True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5]))

Assign new Sub-grade category for valus that have empty space in both grade and subgrade

In [158]:
data_string[:,4] = np.where(data_string[:,4] == '', 'H1', data_string[:,4])

In [159]:
np.unique(data_string[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

**Removing Grade**

In [160]:
data_string = np.delete(data_string, 3, axis=1)


In [161]:
data_string[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [162]:
header_straing = np.delete(header_string, 3)

In [163]:
header_straing

array(['Issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

**Converting Sub-grade to numeric values**

In [164]:
np.unique(data_string[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [165]:
keys = list(np.unique(data_string[:,3]))
values = list(range(1,np.unique(data_string[:,3]).size+1))
dict_sub_grade = dict(zip(keys,values))

In [166]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [167]:
for i in np.unique(data_string[:,3]):
  data_string[:,3] = np.where(data_string[:,3]==i,
                              dict_sub_grade[i],
                              data_string[:,3])

In [168]:
np.unique(data_string[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

**Verification status**

In [169]:
header_straing

array(['Issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [170]:
np.unique(data_string[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

Chnage column values into 0 and 1

In [171]:
data_string[:,4] = np.where((data_string[:,4]=='') | (data_string[:,4]=='Not Verified'),0,1)

In [172]:
np.unique(data_string[:,4])

array(['0', '1'], dtype='<U69')

**URL**

In [173]:
np.unique(data_string[:,5])

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=12606806',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=13026045',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=1312426', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8138291',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8214572',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=849994'], dtype='<U69')

Remove the repeating part

In [174]:
data_string[:,5] = np.chararray.strip(data_string[:,5],"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")
data_string[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [175]:
header

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [176]:
data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [177]:
np.array_equal(data_string[:,5].astype(dtype=int), data_numeric[:,0].astype(dtype=int))

True

In [178]:
data_string = np.delete(data_string,5,axis=1)

In [179]:
header_straing = np.delete(header_straing,5)
header_straing

array(['Issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

**State Address**

In [180]:
header_straing

array(['Issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [181]:
header_straing[5] = 'State_Address'

In [182]:
state_name, state_count = np.unique(data_string[:,5], return_counts=True)

Sort count in decreasing order

In [183]:
state_count_sorted = np.argsort(-state_count)
state_name[state_count_sorted], state_count[state_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10]))

Missing Values

In [184]:
data_string[:,5] = np.where(data_string[:,5]=='',0,data_string[:,5])

Group states to avoid outliers issues.   
west = 1   
south = 2   
midwest = 3   
east = 4

In [185]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [186]:
data_string[:,5] = np.where(np.isin(data_string[:,5],states_west),1,data_string[:,5])
data_string[:,5] = np.where(np.isin(data_string[:,5],states_south),2,data_string[:,5])
data_string[:,5] = np.where(np.isin(data_string[:,5],states_midwest),3,data_string[:,5])
data_string[:,5] = np.where(np.isin(data_string[:,5],states_east),4,data_string[:,5])

In [187]:
np.unique(data_string[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

#**Converting string data to numeric**

In [188]:
data_string

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [189]:
data_string = data_string.astype(int)
data_string

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

##**Checkpoint 1: Strings**

In [190]:
checkpoint_Strings = checkpoint("Checkpoint-Strings", header_straing, data_string)

In [191]:
checkpoint_Strings['header']

array(['Issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'State_Address'], dtype='<U19')

In [192]:
checkpoint_Strings['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

#**Manipulating Numeric columns**

In [193]:
data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [194]:
np.isnan(data_numeric).sum()

0

##**Substitute Filler Values**

In [195]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

**id**

In [196]:
data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [197]:
temp_fill

68616520.0

Check missing values

In [198]:
np.isin(data_numeric[:,0],temp_fill).sum()

0

**Use temporary stats to replace missing values**

In [199]:
col_numeric

array([ 0,  2,  4,  6,  7, 13])

In [200]:
temp_stats[:,col_numeric]
#first row = min values
#sec = mean values
#third = max values

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [201]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

**Funded Amount**   
Replace filler values with the column min

In [202]:
data_numeric[:,2] = np.where(data_numeric[:,2] == temp_fill, temp_stats[0,col_numeric[2]], data_numeric[:,2])
data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

**Loaned Amount, Interest Rate, Total Payment, Installment**   
Replace filler values with the max of each column

In [203]:
data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [204]:
for i in [1,3,4,5]:
  data_numeric[:,i] = np.where(data_numeric[:,i] == temp_fill, temp_stats[2,col_numeric[i]], data_numeric[:,i])

In [205]:
data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

##**Currency change**

**The exchange rate**

In [206]:
EUR_USD = np.genfromtxt("EUR-USD.csv", delimiter = ',', autostrip = True, skip_header = 1, usecols = 3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [207]:
header_string

array(['Issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [208]:
data_string[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [209]:
exchange_rate = data_string[:,0]

for i in range(1,13):
  exchange_rate = np.where(exchange_rate==i,
                           EUR_USD[i-1],
                           exchange_rate)
exchange_rate


array([1.1 , 0.  , 1.13, ..., 1.12, 1.11, 1.09])

Handling missing values   
Missing value = 0

In [210]:
exchange_rate = np.where(exchange_rate==0,
                           np.mean(EUR_USD),
                           exchange_rate)
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

**Add exchange rate to the dataset**

In [211]:
exchange_rate.shape

(10000,)

In [212]:
data_numeric.shape

(10000, 6)

In [213]:
exchange_rate = np.reshape(exchange_rate, (10000,1))
exchange_rate

array([[1.1 ],
       [1.11],
       [1.13],
       ...,
       [1.12],
       [1.11],
       [1.09]])

In [214]:
data_numeric = np.hstack((data_numeric, exchange_rate))


In [215]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [216]:
header_numeric = np.concatenate((header_numeric, np.array(['exchange_rate'])))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

**From USD TO EUR**

In [217]:
columns_dollar = np.array([1,2,4,5])
#'loan_amnt'
#'funded_amnt'
#'installment'
#'total_pymnt'

In [218]:
data_numeric[:,columns_dollar]

array([[35000.  , 35000.  ,  1184.86,  9452.96],
       [30000.  , 30000.  ,   938.57,  4679.7 ],
       [15000.  , 15000.  ,   494.86,  1969.83],
       ...,
       [10000.  , 10000.  ,  1372.97,  2185.64],
       [35000.  , 10000.  ,   354.3 ,  3199.4 ],
       [10000.  , 10000.  ,   309.97,   301.9 ]])

In [219]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [220]:
data_numeric.shape

(10000, 7)

In [221]:
for i in columns_dollar:
    data_numeric = np.hstack((data_numeric, np.reshape(data_numeric[:,i] / data_numeric[:,6], (10000,1))))

In [222]:
data_numeric.shape

(10000, 11)

In [223]:
data_numeric[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

**Expanding the header**

In [224]:
header_additional = np.array([column_name + '_EUR' for column_name in header_numeric[columns_dollar]])
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [225]:
header_numeric = np.concatenate((header_numeric,header_additional))

**Rename dollars column**

In [226]:
header_numeric[columns_dollar] = np.array([column_name + '_USD' for column_name in header_numeric[columns_dollar]])
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

**Reorders the columns**

In [227]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [228]:
header_numeric = header_numeric[columns_index_order]

In [229]:
data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [230]:
data_numeric = data_numeric[:,columns_index_order]

##**Interest Rate**

In [231]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [232]:
data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [233]:
data_numeric[:,5] = data_numeric[:,5]/100

In [234]:
data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

##**Checkpoint 2: Numeric**

In [235]:
checkpoint_numeric = checkpoint("Checkpoint-numeric", header_numeric, data_numeric)

In [236]:
checkpoint_numeric["header"]

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [237]:
checkpoint_numeric["data"]

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

##**Creating the "Complete" Dataset**

In [238]:
checkpoint_Strings['data'].shape

(10000, 6)

In [239]:
checkpoint_numeric["data"].shape

(10000, 11)

In [240]:
loan_data = np.hstack((checkpoint_numeric['data'], checkpoint_Strings['data']))

In [241]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [242]:
np.isnan(loan_data).sum()

0

In [243]:
header_full = np.concatenate((checkpoint_numeric['header'], checkpoint_Strings['header']))
header_full

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'Issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'State_Address'], dtype='<U19')

## **Sorting the New Dataset**

In [244]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [245]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [246]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999])

## **Storing the New Dataset**

In [247]:
loan_data = np.vstack((header_full, loan_data))

In [248]:
np.savetxt("loan-data-preprocessed.csv",
           loan_data,
           fmt = '%s',
           delimiter = ',')